"""uxapp CLI. create-app layers on uxdom. --yes is not --force."""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Sequence

from ux_app._version import __version__
from ux_app.doctor import run as run_doctor
from ux_app.domains import BASELINE, UI, load_bundled
from ux_app.ops import S_PAIRS

CART_APP = '''\
from ux_app import App, Badge, Component


class CartBadge(Component):
    id = "cart.badge"
    count: int = 0

    def render(self):
        return Badge(self.count, on_click=self.add)

    def add(self, sku: str = ""):
        self.count += 1


app = App.boot(title="Cart")
app.add(CartBadge)

if __name__ == "__main__":
    print(app.html("cart.badge"))
    app.click("cart.badge")
    print(app.world.ui["cart.badge"])
'''

COMPONENT_STUB = '''\
from ux_app import Badge, Component


class {cls}(Component):
    id = "{ident}"
    label: str = "{cls}"

    def render(self):
        return Badge(self.label, on_click=self.ping)

    def ping(self):
        return None
'''

ACTION_STUB = '''\
from ux_app import action, notify, update


@action("{name}", caps=())
def {fn}(ctx):
    return [update("content"), *notify("ok")]
'''

DOMAIN_STUB = '''\
# Product domain pack. Register with:
#   app.domain(name="{name}", version="1.0.0", pairs=[("{name}", "apply")], driver=apply)
from ux_app.ops import Op


def apply(op: Op, world) -> None:
    target = op.payload.get("target")
    if not target:
        raise ValueError("{name} missing target")
    world.ui[str(target)] = op.payload
'''


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="uxapp",
        description="Host-authored application layer on ux-dom + ux-channel.",
    )
    parser.add_argument("--version", action="version", version=f"ux-app {__version__}")
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_create = sub.add_parser("create-app", help="Layer App boot on uxdom create-app")
    p_create.add_argument("path")
    p_create.add_argument("--yes", action="store_true", help="non-interactive; not overwrite")
    p_create.add_argument("--force", action="store_true", help="overwrite existing files")

    p_init = sub.add_parser("init", help="Add App boot to the current directory")
    p_init.add_argument("--yes", action="store_true")
    p_init.add_argument("--force", action="store_true")

    p_new = sub.add_parser("new", help="new component|action|domain")
    p_new.add_argument("kind", choices=["component", "action", "domain"])
    p_new.add_argument("name")
    p_new.add_argument("--yes", action="store_true")
    p_new.add_argument("--force", action="store_true")

    p_doctor = sub.add_parser("doctor", help="Isolation, stamp, drivers")
    p_doctor.add_argument("--fail", action="store_true")

    p_explain = sub.add_parser("explain", help="Dump Actions, Components, domains, stamp")

    args = parser.parse_args(list(argv) if argv is not None else None)
    if args.cmd == "create-app":
        return cmd_create_app(Path(args.path), yes=args.yes, force=args.force)
    if args.cmd == "init":
        return cmd_init(Path.cwd(), yes=args.yes, force=args.force)
    if args.cmd == "new":
        return cmd_new(args.kind, args.name, yes=args.yes, force=args.force)
    if args.cmd == "doctor":
        return cmd_doctor(fail=args.fail)
    if args.cmd == "explain":
        return cmd_explain()
    parser.print_help()
    return 2


def _write(path: Path, text: str, *, force: bool, yes: bool) -> bool:
    if path.exists() and not force:
        print(f"skip {path} (exists; pass --force to overwrite)", file=sys.stderr)
        if not yes:
            return False
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    print(f"wrote {path}")
    return True


def cmd_create_app(dest: Path, *, yes: bool, force: bool) -> int:
    dest.mkdir(parents=True, exist_ok=True)
    uxdom = shutil.which("uxdom")
    if uxdom:
        cmd = [uxdom, "create-app", str(dest)]
        if force:
            cmd.append("--force")
        if yes:
            cmd.append("--yes")
        try:
            subprocess.run(cmd, check=False)
        except OSError as exc:
            print(f"uxdom create-app skipped: {exc}", file=sys.stderr)
    else:
        print("uxdom not on PATH; writing App layer only", file=sys.stderr)
    _write(dest / "app.py", CART_APP, force=force, yes=yes)
    readme = (
        "# Cart\n\n"
        "Generated by `uxapp create-app`. Document/routes/Tailwind come from "
        "`uxdom create-app` when that CLI is installed.\n\n"
        "    python app.py\n"
    )
    _write(dest / "README.md", readme, force=force, yes=yes)
    return 0


def cmd_init(dest: Path, *, yes: bool, force: bool) -> int:
    _write(dest / "app.py", CART_APP, force=force, yes=yes)
    return 0


def cmd_new(kind: str, name: str, *, yes: bool, force: bool) -> int:
    slug = name.replace(".", "_").replace("-", "_")
    if kind == "component":
        cls = "".join(part.capitalize() for part in slug.split("_"))
        ident = name if "." in name else f"{slug.replace('_', '.')}"
        text = COMPONENT_STUB.format(cls=cls, ident=ident)
        path = Path(f"{slug}.py")
    elif kind == "action":
        text = ACTION_STUB.format(name=name, fn=slug.split("_")[-1])
        path = Path(f"{slug}.py")
    else:
        text = DOMAIN_STUB.format(name=name)
        path = Path(f"{slug}_domain.py")
    _write(path, text, force=force, yes=yes)
    return 0


def cmd_doctor(*, fail: bool) -> int:
    try:
        issues = run_doctor(None, fail=fail)
    except Exception as exc:
        print(str(exc), file=sys.stderr)
        return 1
    if not issues:
        print("doctor: ok")
        return 0
    for item in issues:
        print(f"- {item}")
    return 1 if fail else 0


def cmd_explain() -> int:
    actions: list[str] = []
    try:
        from ux_app.action import all_actions

        actions = sorted(all_actions())
    except Exception:
        actions = []
    bundled = ["search"]
    try:
        load_bundled("search")
    except Exception:
        bundled = []
    print("Actions:")
    print("  " + (", ".join(actions) if actions else "(none registered)"))
    print("Components:")
    print("  (none — boot an App and call explain() on it)")
    print("Domains:")
    print(f"  core: {BASELINE.name}, {UI.name}")
    print(f"  bundled: {', '.join(bundled) or '(none)'}")
    print("Stamp (S):")
    print("  " + ", ".join(sorted(f"{ns}.{n}" for ns, n in S_PAIRS)))
    print("Drivers:")
    print("  S (kv.set, kv.delete, log.append, ui.dom.morph, ui.dom.restore)")
    return 0
